"""Cloudflare Python Worker for the HUMAN builder. D1 stores wallet blueprints."""
from __future__ import annotations

import io
import json
import re
import secrets
import zipfile

from fastapi import FastAPI, HTTPException, Request, Response
from pydantic import BaseModel, Field
from workers import asgi

from app import brain
from app.catalog import ACCENTS, BY_ID, GROUPS, THEMES, TOTAL_OPTIONS

app = FastAPI(docs_url=None, redoc_url=None, openapi_url=None)
PUBLIC_BASE_URL = "https://buildawallet.xyz"
LIST_FIELDS = ("assets", "networks", "security", "features", "platforms", "privacy")
SINGLE_FIELDS = ("custody", "style", "theme", "accent")
CODE_CHARS = "abcdefghjkmnpqrstuvwxyz23456789"


def clean_spec(raw):
    spec = brain.blank_spec()
    if not isinstance(raw, dict):
        return spec
    spec["name"] = str(raw.get("name") or "")[:32].strip()
    spec["purpose"] = str(raw.get("purpose") or "")[:140].strip()
    for field in LIST_FIELDS:
        values = raw.get(field)
        if isinstance(values, list):
            spec[field] = list(dict.fromkeys(
                item for item in values if isinstance(item, str) and brain.GROUP_OF.get(item) == field
            ))[:200]
    for field in SINGLE_FIELDS:
        value = raw.get(field)
        if isinstance(value, str) and brain.GROUP_OF.get(value) == field:
            spec[field] = value
    spec["theme"] = spec.get("theme") or "t_dark"
    spec["accent"] = spec.get("accent") or "a_green"
    return spec


def clean_state(raw):
    state = brain.fresh_state()
    if not isinstance(raw, dict):
        return state
    for key in ("asked", "answered", "skipped", "said", "pending"):
        if isinstance(raw.get(key), list):
            state[key] = [str(value)[:40] for value in raw[key][:400]]
    for key in ("current", "last_q"):
        if isinstance(raw.get(key), str):
            state[key] = raw[key][:200]
    if isinstance(raw.get("turns"), int):
        state["turns"] = max(0, min(raw["turns"], 100000))
    state["finished"] = bool(raw.get("finished"))
    return state


class ChatIn(BaseModel):
    message: str = Field(default="", max_length=600)
    spec: dict | None = None
    state: dict | None = None


class SaveIn(BaseModel):
    spec: dict | None = None
    is_public: bool = False


class ApkPackageIn(BaseModel):
    spec: dict | None = None
    app_name: str = Field(default="BuildAWallet", max_length=40)
    package_name: str = Field(default="xyz.buildawallet.app", max_length=120)


def database(request: Request):
    env = request.scope.get("env")
    if env is None or getattr(env, "DB", None) is None:
        raise HTTPException(503, "Blueprint storage is unavailable")
    return env.DB


def row_py(row):
    return row.to_py() if hasattr(row, "to_py") else row


def safe_package_name(value: str) -> str:
    value = (value or "").strip().lower()
    if not re.fullmatch(r"[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+", value):
        raise HTTPException(400, "package_name must look like xyz.example.wallet")
    return value[:120]


def kotlin_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


def android_project(spec: dict, app_name: str, package_name: str) -> bytes:
    app_name = (app_name or spec.get("name") or "BuildAWallet").strip()[:40] or "BuildAWallet"
    package_name = safe_package_name(package_name)
    spec_json = json.dumps(spec, separators=(",", ":"), ensure_ascii=False)
    spec_kt = kotlin_string(spec_json)
    label_xml = app_name.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    activity_path = package_name.replace(".", "/")

    files = {
        "README.md": f"""# {app_name} Android wrapper\n\nThis project is generated by BuildAWallet.xyz. It opens the HUMAN Studio in an Android WebView and injects this wallet blueprint into the app's local storage so the phone starts with the same configuration selected in the web builder.\n\n## Build\n\n1. Open this folder in Android Studio, or use a JDK 17+ shell.\n2. Run `./gradlew assembleDebug` if you add/use a Gradle wrapper, or build with Android Studio.\n3. The debug APK is produced under `app/build/outputs/apk/debug/`.\n\nThe wrapper does not export private keys or seed phrases. Network-dependent wallet capabilities remain provided by the BuildAWallet web application.\n""",
        "settings.gradle.kts": f"""pluginManagement {{ repositories {{ google(); mavenCentral(); gradlePluginPortal() }} }}\ndependencyResolutionManagement {{ repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories {{ google(); mavenCentral() }} }}\nrootProject.name = \"{kotlin_string(app_name)}\"\ninclude(\":app\")\n""",
        "build.gradle.kts": """plugins {\n    id(\"com.android.application\") version \"8.9.1\" apply false\n    id(\"org.jetbrains.kotlin.android\") version \"2.1.20\" apply false\n}\n""",
        "gradle.properties": """org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nkotlin.code.style=official\n""",
        "app/build.gradle.kts": f"""plugins {{\n    id(\"com.android.application\")\n    id(\"org.jetbrains.kotlin.android\")\n}}\n\nandroid {{\n    namespace = \"{package_name}\"\n    compileSdk = 35\n\n    defaultConfig {{\n        applicationId = \"{package_name}\"\n        minSdk = 26\n        targetSdk = 35\n        versionCode = 1\n        versionName = \"1.0\"\n    }}\n}}\n\ndependencies {{\n    implementation(\"androidx.core:core-ktx:1.15.0\")\n    implementation(\"androidx.activity:activity-ktx:1.10.1\")\n}}\n""",
        "app/src/main/AndroidManifest.xml": f"""<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\">\n    <uses-permission android:name=\"android.permission.INTERNET\" />\n    <application android:allowBackup=\"false\" android:label=\"{label_xml}\" android:usesCleartextTraffic=\"false\" android:theme=\"@style/AppTheme\">\n        <activity android:name=\".MainActivity\" android:exported=\"true\">\n            <intent-filter>\n                <action android:name=\"android.intent.action.MAIN\" />\n                <category android:name=\"android.intent.category.LAUNCHER\" />\n            </intent-filter>\n        </activity>\n    </application>\n</manifest>\n""",
        "app/src/main/res/values/styles.xml": """<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<resources>\n    <style name=\"AppTheme\" parent=\"android:style/Theme.Material.Light.NoActionBar\">\n        <item name=\"android:fontFamily\">sans</item>\n        <item name=\"android:windowLightStatusBar\">false</item>\n        <item name=\"android:statusBarColor\">#071009</item>\n        <item name=\"android:navigationBarColor\">#071009</item>\n    </style>\n</resources>\n""",
        f"app/src/main/java/{activity_path}/MainActivity.kt": f"""package {package_name}\n\nimport android.annotation.SuppressLint\nimport android.os.Bundle\nimport android.webkit.WebChromeClient\nimport android.webkit.WebView\nimport android.webkit.WebViewClient\nimport androidx.activity.ComponentActivity\nimport org.json.JSONObject\n\nclass MainActivity : ComponentActivity() {{\n    private val walletSpec = \"{spec_kt}\"\n\n    @SuppressLint(\"SetJavaScriptEnabled\")\n    override fun onCreate(savedInstanceState: Bundle?) {{\n        super.onCreate(savedInstanceState)\n        val web = WebView(this)\n        web.settings.javaScriptEnabled = true\n        web.settings.domStorageEnabled = true\n        web.settings.databaseEnabled = true\n        web.settings.allowFileAccess = false\n        web.settings.allowContentAccess = false\n        web.webChromeClient = WebChromeClient()\n        web.webViewClient = object : WebViewClient() {{\n            override fun onPageFinished(view: WebView, url: String) {{\n                super.onPageFinished(view, url)\n                val quoted = JSONObject.quote(walletSpec)\n                view.evaluateJavascript(\"localStorage.setItem('baw_human_spec_v1', \" + quoted + \");\", null)\n            }}\n        }}\n        setContentView(web)\n        web.loadUrl(\"https://buildawallet.xyz/human/studio\")\n    }}\n\n    @Deprecated(\"Deprecated in Java\")\n    override fun onBackPressed() {{\n        val web = findViewById<WebView>(android.R.id.content)?.rootView as? WebView\n        if (web != null && web.canGoBack()) web.goBack() else super.onBackPressed()\n    }}\n}}\n""",
        "wallet-blueprint.json": json.dumps(spec, indent=2, ensure_ascii=False),
    }

    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path, content in files.items():
            zf.writestr(path, content)
    return out.getvalue()


@app.get("/healthz")
async def healthz(request: Request):
    try:
        db = database(request)
        await db.prepare("SELECT 1 FROM wallets LIMIT 1").run()
        return {"ok": True, "builder": "available", "apk_packaging": True, "agent_api": "not deployed"}
    except Exception:
        raise HTTPException(503, "Builder storage is unavailable")


@app.get("/api/start")
async def start():
    return brain.opening()


@app.post("/api/chat")
async def chat(body: ChatIn):
    return brain.respond(body.message, clean_spec(body.spec), clean_state(body.state))


@app.get("/api/catalog")
async def catalog():
    return {
        "groups": [{"key": group["key"], "title": group["title"], "multi": group["multi"],
                    "items": [{key: item.get(key, "") for key in ("id", "label", "blurb", "sym", "color", "tab")}
                              for item in group["items"]]} for group in GROUPS],
        "themes": [{key: theme[key] for key in ("id", "label", "mode")} for theme in THEMES],
        "accents": [{key: accent[key] for key in ("id", "label", "hex")} for accent in ACCENTS],
        "total": TOTAL_OPTIONS,
        "meta": {item_id: {key: item.get(key, "") for key in ("label", "sym", "color")}
                 for item_id, item in BY_ID.items()},
    }


@app.post("/api/save")
async def save(body: SaveIn, request: Request):
    spec = clean_spec(body.spec)
    if brain.filled_count(spec) < 1:
        raise HTTPException(400, "nothing to save yet")
    db = database(request)
    for _ in range(5):
        code = "".join(secrets.choice(CODE_CHARS) for _ in range(26))
        try:
            await db.prepare("INSERT INTO wallets(code,name,spec,is_public) VALUES(?,?,?,?)").bind(
                code, spec["name"] or "Untitled wallet", json.dumps(spec), int(body.is_public)
            ).run()
            return {"code": code, "url": f"{PUBLIC_BASE_URL}/w/{code}"}
        except Exception as exc:
            if "UNIQUE" not in str(exc):
                raise HTTPException(503, "Blueprint storage failed") from exc
    raise HTTPException(503, "could not allocate a code")


@app.post("/api/apk-package")
async def apk_package(body: ApkPackageIn):
    spec = clean_spec(body.spec)
    if brain.filled_count(spec) < 1:
        raise HTTPException(400, "choose at least one wallet option before packaging")
    raw = android_project(spec, body.app_name, body.package_name)
    base = re.sub(r"[^A-Za-z0-9._-]+", "_", body.app_name.strip() or spec.get("name") or "wallet")[:48]
    return Response(
        content=raw,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="{base}-android-wallet.zip"', "Cache-Control": "no-store"},
    )


@app.get("/api/gallery")
async def gallery(request: Request):
    result = await database(request).prepare(
        "SELECT name,code,spec FROM wallets WHERE is_public=1 ORDER BY created_at DESC LIMIT 24"
    ).run()
    return {"items": [{"name": row["name"], "code": row["code"],
                       "count": brain.filled_count(json.loads(row["spec"]))}
                      for row in row_py(result.results)]}


@app.get("/api/wallet/{code}")
async def saved(code: str, request: Request):
    row = await database(request).prepare(
        "SELECT code,name,spec,created_at FROM wallets WHERE code=?"
    ).bind(code[:32].lower()).first()
    if row is None:
        raise HTTPException(404, "no wallet with that code")
    record = row_py(row)
    return {"code": record["code"], "name": record["name"],
            "created_at": record["created_at"], "spec": clean_spec(json.loads(record["spec"]))}


@app.get("/api/stats")
async def stats(request: Request):
    db = database(request)
    count = row_py(await db.prepare("SELECT COUNT(*) AS n FROM wallets").first())
    return {"built": count["n"], "options": TOTAL_OPTIONS}


Default = asgi.entrypoint(app)
