"""The Build-a-Wallet option catalog.

Everything the wallet architect can offer lives here: assets, networks,
custody models, security layers, features, platforms, privacy tooling and
finish. Each option carries the keywords the language engine matches on and a
one-line blurb it can read back when somebody asks "what is that?".
"""

from __future__ import annotations


def opt(id, label, kw, blurb, **extra):
    d = {"id": id, "label": label, "kw": kw, "blurb": blurb}
    d.update(extra)
    return d


# ---------------------------------------------------------------- assets ----
ASSETS = [
    opt("btc", "Bitcoin", ["bitcoin", "btc", "satoshi", "sats"],
        "The original chain. UTXO based, so the wallet needs its own address and coin handling.",
        sym="BTC", color="#f7931a"),
    opt("eth", "Ethereum", ["ethereum", "eth", "ether"],
        "Smart contract chain. Unlocks tokens, NFTs, DeFi and every L2 in the list.",
        sym="ETH", color="#7b8cf5"),
    opt("sol", "Solana", ["solana", "sol"],
        "Fast and cheap, with its own SPL token standard and its own address format.",
        sym="SOL", color="#14f195"),
    opt("xrp", "XRP", ["xrp", "ripple"],
        "Payment focused ledger with built in destination tags for exchanges.",
        sym="XRP", color="#9aa3b2"),
    opt("ada", "Cardano", ["cardano", "ada"],
        "UTXO smart contract chain with native staking baked into the protocol.",
        sym="ADA", color="#3468d1"),
    opt("doge", "Dogecoin", ["dogecoin", "doge"],
        "Cheap transfers, huge retail recognition, very simple to support.",
        sym="DOGE", color="#c3a634"),
    opt("ltc", "Litecoin", ["litecoin", "ltc"],
        "Bitcoin style chain with faster blocks. Shares most of the BTC code path.",
        sym="LTC", color="#a6b0c3"),
    opt("bnb", "BNB Chain", ["bnb", "binance coin", "bsc", "binance smart chain"],
        "EVM chain with low fees and a deep retail token market.",
        sym="BNB", color="#f0b90b"),
    opt("avax", "Avalanche", ["avalanche", "avax"],
        "EVM compatible with subnets, so app specific chains are easy to add later.",
        sym="AVAX", color="#e84142"),
    opt("dot", "Polkadot", ["polkadot", "dot"],
        "Parachain hub. Adding it opens the door to the whole Substrate family.",
        sym="DOT", color="#e6007a"),
    opt("atom", "Cosmos", ["cosmos", "atom", "ibc"],
        "IBC lets one integration reach dozens of app chains.",
        sym="ATOM", color="#6f7bf7"),
    opt("ton", "TON", ["ton", "toncoin", "telegram coin"],
        "Telegram's chain. Pairs naturally with a Telegram mini app front end.",
        sym="TON", color="#0098ea"),
    opt("trx", "Tron", ["tron", "trx"],
        "Carries an enormous share of USDT transfers, especially for remittances.",
        sym="TRX", color="#eb0029"),
    opt("sui", "Sui", ["sui"],
        "Object model chain with sponsored transactions built in.",
        sym="SUI", color="#4da2ff"),
    opt("apt", "Aptos", ["aptos", "apt"],
        "Move language chain, fast finality, growing payments footprint.",
        sym="APT", color="#9bb0c9"),
    opt("near", "NEAR", ["near protocol", "near"],
        "Human readable account names instead of hex addresses.",
        sym="NEAR", color="#bdbdbd"),
    opt("xlm", "Stellar", ["stellar", "xlm", "lumens"],
        "Built for cheap cross border payments and asset issuance.",
        sym="XLM", color="#8fa6d8"),
    opt("xmr", "Monero", ["monero", "xmr"],
        "Private by default. Needs its own view key handling and its own node policy.",
        sym="XMR", color="#ff6600"),
    opt("zec", "Zcash", ["zcash", "zec", "shielded"],
        "Optional shielded transfers using zero knowledge proofs.",
        sym="ZEC", color="#ecb244"),
    opt("link", "Chainlink", ["chainlink", "link"],
        "ERC-20, so it arrives free with Ethereum token support.",
        sym="LINK", color="#375bd2"),
    opt("matic", "Polygon", ["polygon", "matic", "pol"],
        "Cheap EVM chain, very common first stop for new users.",
        sym="POL", color="#8247e5"),
    opt("usdc", "USDC", ["usdc", "circle"],
        "Regulated dollar stablecoin. The default unit of account for most wallets.",
        sym="USDC", color="#2775ca"),
    opt("usdt", "USDT", ["usdt", "tether"],
        "The most traded stablecoin worldwide, biggest on Tron and Ethereum.",
        sym="USDT", color="#26a17b"),
    opt("dai", "DAI", ["dai", "makerdao"],
        "Crypto collateralized dollar with no company able to freeze it.",
        sym="DAI", color="#f5ac37"),
    opt("eurc", "Euro stablecoin", ["eurc", "euro stablecoin", "eur stable"],
        "A euro denominated unit for European users who do not think in dollars.",
        sym="EURC", color="#5b8def"),
    opt("meme", "Memecoins", ["memecoin", "meme coins", "meme", "shib", "pepe", "bonk", "wif"],
        "Long tail tokens. Needs a scam filter and a token metadata source to stay usable.",
        sym="MEME", color="#ff5fa2"),
    opt("erc20", "Any ERC-20 token", ["erc20", "erc-20", "custom token", "any token", "all tokens"],
        "Paste a contract address and the token shows up with its icon and price.",
        sym="ERC20", color="#98a2b3"),
    opt("nft_asset", "NFTs and collectibles", ["nft", "nfts", "collectible", "collectibles"],
        "Media heavy assets, so they get their own tab rather than sitting in the token list.",
        sym="NFT", color="#c084fc"),
    opt("rwa", "Tokenized real world assets", ["rwa", "real world asset", "tokenized treasury", "t-bill", "tbill"],
        "Tokenized treasuries and funds, usually with a permissioned transfer check.",
        sym="RWA", color="#7dd3a0"),
]

# --------------------------------------------------------------- networks ---
NETWORKS = [
    opt("n_eth", "Ethereum mainnet", ["ethereum mainnet", "mainnet", "l1"],
        "Settlement layer. Expensive, so most wallets pair it with an L2."),
    opt("n_base", "Base", ["base network", "base chain", "base"],
        "Coinbase's L2. Cheap, and the easiest on-ramp path for US users."),
    opt("n_arb", "Arbitrum", ["arbitrum", "arb"],
        "Largest L2 by DeFi liquidity."),
    opt("n_op", "Optimism", ["optimism", "op mainnet"],
        "OP Stack L2, shares tooling with Base."),
    opt("n_zk", "zkSync / Linea / Scroll", ["zksync", "linea", "scroll", "zk rollup", "zkevm"],
        "Zero knowledge rollups with native account abstraction support."),
    opt("n_poly", "Polygon PoS", ["polygon pos", "polygon network"],
        "Very cheap EVM chain with strong gaming and payments use."),
    opt("n_ln", "Bitcoin Lightning", ["lightning", "ln", "lightning network"],
        "Instant sub-cent Bitcoin payments. Needs channel or LSP management."),
    opt("n_liquid", "Bitcoin L2 (Liquid, Rootstock)", ["liquid", "rootstock", "rsk", "bitcoin l2"],
        "Sidechains that add confidential transfers or contracts to Bitcoin."),
    opt("n_ibc", "Cosmos IBC zones", ["ibc", "cosmos zones", "osmosis"],
        "One integration, many app chains, with native cross chain transfers."),
    opt("n_test", "Testnets", ["testnet", "sepolia", "devnet", "test network"],
        "A network switcher with faucets, for people who want to try before funding."),
    opt("n_custom", "Custom RPC networks", ["custom rpc", "add network", "custom chain", "any evm"],
        "Users paste a chain ID and RPC URL and the wallet supports it immediately."),
]

# ---------------------------------------------------------------- custody ---
CUSTODY = [
    opt("c_seed", "Self custody with a seed phrase", ["seed phrase", "self custody", "12 words", "24 words", "mnemonic", "not your keys"],
        "The classic model. Twelve or twenty four words, written down, full control and full responsibility."),
    opt("c_mpc", "MPC keyless (no seed phrase)", ["mpc", "keyless", "no seed", "key shares", "threshold signature", "tss"],
        "The key is split into shares that never meet. Users sign in with a passkey or email and still hold a share."),
    opt("c_aa", "Smart account (account abstraction)", ["smart account", "account abstraction", "erc-4337", "4337", "smart wallet"],
        "The account is a contract, which unlocks sponsored gas, batching, session keys and recovery rules."),
    opt("c_hw", "Hardware first", ["hardware wallet", "ledger", "trezor", "cold storage", "cold wallet"],
        "Keys never leave a signing device. The app becomes a watch and broadcast layer."),
    opt("c_multisig", "Multisig vault", ["multisig", "multi-sig", "2 of 3", "3 of 5", "co-signer", "safe"],
        "Several signers must approve. The right answer for treasuries, partners and large balances."),
    opt("c_custodial", "Custodial (you hold the keys for users)", ["custodial", "we hold keys", "exchange style", "managed keys"],
        "Simplest for newcomers, but it makes you a regulated party in most places."),
    opt("c_hybrid", "Hybrid: custodial start, self custody upgrade", ["hybrid custody", "graduate", "upgrade to self custody", "progressive custody"],
        "Users start with training wheels and export to full self custody when they are ready."),
]

# --------------------------------------------------------------- security ---
SECURITY = [
    opt("s_bio", "Biometric unlock", ["biometric", "face id", "faceid", "fingerprint", "touch id"],
        "Face or fingerprint to open the app and to confirm spending."),
    opt("s_pin", "PIN or password", ["pin", "passcode", "password"],
        "A local secret, the baseline for anything on a phone."),
    opt("s_passkey", "Passkeys", ["passkey", "passkeys", "webauthn", "fido"],
        "Phishing resistant sign-in backed by the device secure element."),
    opt("s_2fa", "Two factor for sensitive actions", ["2fa", "two factor", "mfa", "authenticator", "otp"],
        "A second factor on withdrawals, exports and new device logins."),
    opt("s_social", "Social recovery", ["social recovery", "guardian", "guardians", "trusted contacts", "recover with friends"],
        "Chosen guardians can restore access without ever seeing the key."),
    opt("s_shamir", "Split backup (Shamir shares)", ["shamir", "split backup", "sss", "backup shares"],
        "The backup is split into pieces, any threshold of them restores it."),
    opt("s_cloud", "Encrypted cloud backup", ["icloud backup", "cloud backup", "google drive backup", "encrypted backup"],
        "An encrypted blob in the user's own cloud, unlocked by a password only they know."),
    opt("s_hwsupport", "Hardware wallet pairing", ["connect ledger", "pair hardware", "hardware support"],
        "Pair a signing device for large balances while keeping the same interface."),
    opt("s_sim", "Transaction simulation", ["simulate", "simulation", "preview transaction", "what will happen", "tenderly"],
        "Shows exactly what leaves the wallet before the user signs. The single best scam defence."),
    opt("s_scam", "Scam and spam token filter", ["scam filter", "spam token", "phishing", "blocklist", "airdrop spam"],
        "Hides hostile airdrops and flags known drainer contracts and lookalike domains."),
    opt("s_allow", "Address allowlist", ["allowlist", "whitelist", "trusted addresses"],
        "Funds can only leave to addresses approved earlier, with a cooling off delay."),
    opt("s_limits", "Spending limits", ["spending limit", "daily limit", "velocity limit", "cap"],
        "Per day or per transaction caps that need a stronger approval to exceed."),
    opt("s_delay", "Time locked withdrawals", ["timelock", "time lock", "withdrawal delay", "cooldown"],
        "Large transfers wait, and the user can cancel during the window."),
    opt("s_approve", "Token approval manager", ["approvals", "revoke", "allowance", "revoke access"],
        "Lists every contract that can move funds and revokes them in one tap."),
    opt("s_duress", "Duress mode and hidden wallets", ["duress", "decoy", "hidden wallet", "plausible deniability", "panic"],
        "A second PIN opens a decoy wallet holding a small balance."),
    opt("s_autolock", "Auto lock and screenshot block", ["auto lock", "autolock", "screenshot", "screen protection"],
        "Locks on background and stops the balance appearing in screenshots or app switchers."),
    opt("s_audit", "Third party audit and bug bounty", ["audit", "audited", "bug bounty", "pentest"],
        "An external review plus a standing bounty. Table stakes for anything holding real money."),
    opt("s_open", "Open source and reproducible builds", ["open source", "opensource", "verifiable build", "reproducible"],
        "Anyone can verify the shipped app matches the published code."),
    opt("s_inherit", "Inheritance plan", ["inheritance", "dead man switch", "estate", "next of kin", "legacy"],
        "If the wallet goes untouched for a chosen period, a nominated person gains access."),
    opt("s_airgap", "Air gapped signing", ["air gap", "airgap", "qr signing", "offline signing"],
        "Sign on a device that never touches the internet, passing QR codes back and forth."),
]

# --------------------------------------------------------------- features ---
FEATURES = [
    opt("f_send", "Send and receive", ["send", "receive", "transfer", "pay"],
        "The floor. Address, QR, amount, fee choice, confirmation.", core=True, tab="Send"),
    opt("f_swap", "In-app swap", ["swap", "exchange", "trade", "convert", "dex aggregator"],
        "Best price routing across exchanges without leaving the wallet.", tab="Swap"),
    opt("f_bridge", "Cross chain bridge", ["bridge", "cross chain", "move between chains"],
        "Move assets between chains, ideally hidden behind a single swap screen.", tab="Bridge"),
    opt("f_stake", "Staking", ["stake", "staking", "validator", "delegate", "earn rewards"],
        "Earn protocol rewards directly, with clear unbonding times.", tab="Stake"),
    opt("f_earn", "DeFi earn and vaults", ["earn", "yield", "vault", "apy", "lending", "aave", "defi"],
        "Curated yield strategies with the risk stated in plain language.", tab="Earn"),
    opt("f_borrow", "Borrow against holdings", ["borrow", "loan", "collateral", "leverage"],
        "Take a stablecoin loan without selling, with a visible liquidation line."),
    opt("f_nft", "NFT gallery", ["nft gallery", "collectibles tab", "show nfts"],
        "Grid view, traits, floor price, and a send flow that shows the artwork.", tab="NFTs"),
    opt("f_dapp", "dApp browser", ["dapp browser", "browser", "web3 browser", "browse dapps"],
        "An in-app browser with the wallet injected, plus a curated app list.", tab="Apps"),
    opt("f_wc", "WalletConnect", ["walletconnect", "connect to sites", "wc"],
        "Scan a QR to sign into any app on desktop."),
    opt("f_onramp", "Buy with card or bank", ["buy crypto", "buy with card", "onramp", "on-ramp", "card purchase", "fiat", "apple pay", "deposit", "add money", "add funds", "top up balance"],
        "Card, bank transfer or Apple Pay, with the provider chosen per country.", tab="Buy"),
    opt("f_offramp", "Sell to bank", ["sell", "offramp", "off-ramp", "cash out", "withdraw to bank", "cash out to bank", "to a bank account"],
        "The exit route. Often the deciding feature for non-crypto natives."),
    opt("f_card", "Crypto debit card", ["debit card", "crypto card", "spend card", "visa", "mastercard"],
        "Spend balances anywhere, with the conversion happening at the till.", tab="Card"),
    opt("f_portfolio", "Portfolio and P&L", ["portfolio", "pnl", "p&l", "performance", "charts", "graph", "balance history"],
        "Total value over time, cost basis, and per asset performance.", tab="Portfolio"),
    opt("f_alerts", "Price alerts", ["price alert", "alerts", "notify me", "notification"],
        "Push notifications on price moves, incoming funds and governance votes."),
    opt("f_dca", "Recurring buys (DCA)", ["dca", "recurring buy", "auto invest", "weekly buy", "monthly buy", "dollar cost"],
        "Automatic buys on a schedule, the least stressful way to accumulate."),
    opt("f_limit", "Limit orders", ["limit order", "stop loss", "take profit", "trigger order"],
        "Set a price and let it fill while the app is closed."),
    opt("f_book", "Address book", ["address book", "contacts", "saved addresses"],
        "Named contacts with a per contact note, so nobody pastes an address twice."),
    opt("f_names", "Usernames and ENS", ["ens", "username", "domain", "human readable", ".eth", "handle"],
        "Send to alice.eth instead of a forty character string."),
    opt("f_qr", "QR and tap to pay", ["qr", "scan", "nfc", "tap to pay", "in person"],
        "Point of sale style payments face to face."),
    opt("f_request", "Payment requests and invoices", ["request money", "invoice", "payment link", "payment request", "request payment"],
        "A shareable link or QR with the amount and reason baked in."),
    opt("f_split", "Split bills with friends", ["split bill", "split the bill", "group expense", "settle up"],
        "Group tabs that settle in one transaction."),
    opt("f_gas", "Sponsored gas / gas tank", ["gas tank", "sponsored gas", "gasless", "no gas", "pay fees in usdc", "paymaster"],
        "Users pay fees in the token they hold, or you cover them entirely."),
    opt("f_batch", "Batched transactions", ["batch", "one tap approve and swap", "bundle"],
        "Approve and swap in a single confirmation instead of two."),
    opt("f_session", "Session keys", ["session key", "session keys", "game session", "auto sign"],
        "Scoped permissions so a game or bot can act without asking every time."),
    opt("f_multi", "Multiple accounts and folders", ["multiple accounts", "sub accounts", "profiles", "separate wallets"],
        "Separate spending, savings and experiments without switching apps."),
    opt("f_watch", "Watch only wallets", ["watch only", "track address", "watch address"],
        "Track a cold wallet or a friend's address without any keys."),
    opt("f_history", "Rich transaction history", ["history", "activity", "transactions list", "receipts"],
        "Human readable activity: swapped, staked, minted, not just hashes."),
    opt("f_tax", "Tax and CSV export", ["tax", "csv", "export", "accountant", "hmrc", "irs"],
        "Cost basis reports and a clean export for an accountant."),
    opt("f_dao", "DAO governance voting", ["dao", "governance", "vote", "proposal", "snapshot"],
        "See proposals and vote or delegate from the wallet."),
    opt("f_airdrop", "Airdrop and rewards tracker", ["airdrop", "points", "rewards tracker", "eligibility"],
        "Shows what the connected addresses qualify for and what is unclaimed."),
    opt("f_radar", "Token radar and trending", ["trending", "radar", "discover tokens", "new pairs", "market"],
        "What is moving right now, with liquidity and holder checks attached."),
    opt("f_whale", "On-chain alerts and whale watch", ["whale", "on-chain alert", "smart money", "wallet tracking"],
        "Follow interesting addresses and get pinged when they move."),
    opt("f_news", "Market news feed", ["news", "feed", "research"],
        "A short daily brief tied to the assets actually held."),
    opt("f_learn", "Learn and earn tutorials", ["learn", "tutorial", "education", "onboarding lessons", "academy"],
        "Short lessons that pay a tiny reward, the best converter for first time users."),
    opt("f_goals", "Savings goals and round ups", ["savings goal", "round up", "roundup", "piggy bank", "save"],
        "Spare change from card spending sweeps into a savings pot."),
    opt("f_family", "Family and kid accounts", ["family", "kids", "child account", "allowance", "parent"],
        "Supervised accounts with limits and an approval step for the adult."),
    opt("f_business", "Business treasury tools", ["treasury", "business account", "company", "accounting", "bookkeeping"],
        "Roles, policies, cost centres and an export your accountant will accept."),
    opt("f_payroll", "Payroll and mass payouts", ["payroll", "mass payout", "batch pay", "pay contractors", "salaries"],
        "Pay a list of people in one signed batch, with receipts."),
    opt("f_remit", "Remittances and FX", ["remittance", "send money home", "sending money home", "money home", "send money abroad", "fx", "cross border", "corridor", "philippines", "nigeria", "mexico"],
        "Local currency in, local currency out, with the crypto rail invisible."),
    opt("f_merchant", "Merchant and checkout tools", ["merchant", "checkout", "point of sale", "accept payments", "shop"],
        "Take payments as a business, with settlement to stablecoins or bank."),
    opt("f_tip", "Tipping and creator payouts", ["tip", "tipping", "creator", "donation", "support me"],
        "One tap tips to a handle, with a public tip page."),
    opt("f_game", "Gaming and in-game assets", ["gaming", "game", "in-game", "play to earn"],
        "Fast signing, session keys and an inventory view instead of a token list."),
    opt("f_chat", "Encrypted chat and pay by handle", ["chat", "message", "messaging", "dm"],
        "Message a contact and attach money to the message."),
    opt("f_widget", "Home screen widgets", ["widget", "widgets", "home screen"],
        "Balance and price at a glance without opening the app."),
    opt("f_voice", "Voice and accessibility", ["voice", "accessibility", "screen reader", "large text", "a11y"],
        "Screen reader labels, large type and voice confirmation of amounts."),
    opt("f_i18n", "Multi language and local currency", ["language", "languages", "localization", "translate", "local currency"],
        "Display in the user's language and their home currency, not just USD."),
    opt("f_support", "In-app human support", ["support", "help", "live chat", "customer service"],
        "A real person reachable from inside the app, with the context attached."),
    opt("f_ai", "Built-in AI copilot", ["ai assistant", "copilot", "ai helper", "chatbot", "explain this"],
        "Explains transactions, warns about risk and answers questions in plain language."),
    opt("f_pay_bills", "Bill pay and top ups", ["bill", "bills", "utility", "mobile top up", "airtime"],
        "Pay utilities or top up a phone straight from the balance."),
    opt("f_launch", "Token launchpad", ["launchpad", "launch a token", "presale", "ido"],
        "Create or join token launches with vesting and lock rules."),
    opt("f_inherit_tab", "Vault mode for long term holding", ["vault mode", "cold storage mode", "long term", "hodl"],
        "A locked down profile with no browser, no swaps, and deliberate friction."),
]

# -------------------------------------------------------------- platforms ---
PLATFORMS = [
    opt("p_ios", "iOS app", ["ios", "iphone", "apple", "app store"],
        "Face ID, secure enclave, widgets and Apple Pay on-ramp."),
    opt("p_android", "Android app", ["android", "google play", "pixel", "samsung"],
        "Widest global reach, especially in emerging markets."),
    opt("p_web", "Web app", ["web app", "website", "browser app", "web"],
        "Nothing to install. Pairs best with MPC or passkey custody."),
    opt("p_ext", "Browser extension", ["extension", "chrome extension", "browser plugin", "metamask style"],
        "Where desktop DeFi actually happens."),
    opt("p_desktop", "Desktop app", ["desktop", "mac app", "windows", "linux"],
        "Room for pro layouts, multiple accounts and hardware devices."),
    opt("p_tg", "Telegram mini app", ["telegram", "mini app", "miniapp", "bot"],
        "Zero install distribution inside a chat, huge for TON and referrals."),
    opt("p_watch", "Watch app", ["watch", "apple watch", "wearable"],
        "Balance glance and payment confirmation on the wrist."),
    opt("p_hw", "Your own hardware device", ["own hardware", "build hardware", "signing device", "make a device"],
        "A dedicated signer you ship yourself. Serious project, serious moat."),
    opt("p_api", "Developer API and SDK", ["api", "sdk", "developers", "embed", "white label"],
        "Let other products embed the wallet. This is where B2B revenue lives."),
]

# ---------------------------------------------------------------- privacy ---
PRIVACY = [
    opt("v_nokyc", "No KYC for self custody", ["no kyc", "without kyc", "anonymous", "no id"],
        "No identity check to hold or send. On-ramps still verify, so keep them optional."),
    opt("v_tor", "Tor or proxy routing", ["tor", "proxy", "vpn", "hide ip", "onion"],
        "Requests do not leak the user's IP to indexers."),
    opt("v_node", "Own node / private RPC", ["own node", "private rpc", "self host node", "electrum server"],
        "Balances are not queried through a third party that logs everything."),
    opt("v_coin", "Coin control and labels", ["coin control", "utxo", "label coins", "avoid merging"],
        "Choose which coins to spend so histories are not linked."),
    opt("v_stealth", "Stealth addresses", ["stealth address", "new address each time", "silent payments"],
        "A fresh receiving address per payment, automatically."),
    opt("v_noanalytics", "No analytics, no tracking", ["no analytics", "no tracking", "no telemetry", "privacy policy"],
        "No third party SDKs watching what users hold."),
    opt("v_local", "Local only history", ["local history", "on device", "nothing on servers", "offline data"],
        "Transaction history and labels stay encrypted on the device."),
    opt("v_zk", "Zero knowledge proof of funds", ["zk proof", "proof of funds", "prove balance"],
        "Prove you hold enough without revealing the balance or the address."),
]

# ----------------------------------------------------------------- finish ---
THEMES = [
    opt("t_dark", "Dark", ["dark mode", "dark", "black"], "Default for most crypto users.", mode="dark"),
    opt("t_light", "Light", ["light mode", "light", "white", "bright"], "Friendlier for finance-first audiences.", mode="light"),
]

STYLES = [
    opt("st_minimal", "Calm and minimal", ["minimal", "clean", "simple", "calm", "banking"],
        "Quiet type, lots of space, nothing shouting."),
    opt("st_neon", "Neon and cyber", ["neon", "cyber", "cyberpunk", "glow", "degen", "hacker"],
        "High contrast, glowing accents, made for night use."),
    opt("st_glass", "Glass and gradient", ["glass", "gradient", "glassmorphism", "frosted", "aurora"],
        "Soft blurred panels over colour."),
    opt("st_brutal", "Bold and blocky", ["brutalist", "bold", "blocky", "chunky", "retro"],
        "Thick borders, hard shadows, unmistakable."),
    opt("st_play", "Playful", ["playful", "fun", "friendly", "cute", "rounded"],
        "Rounded shapes and warm colour, aimed at first timers."),
]

ACCENTS = [
    {"id": "a_green", "label": "Green", "kw": ["green", "mint", "emerald"], "hex": "#2fe08a"},
    {"id": "a_blue", "label": "Blue", "kw": ["blue", "azure", "cobalt"], "hex": "#4c8dff"},
    {"id": "a_purple", "label": "Purple", "kw": ["purple", "violet", "lilac"], "hex": "#a06bff"},
    {"id": "a_orange", "label": "Orange", "kw": ["orange", "amber", "bitcoin orange"], "hex": "#ff9f43"},
    {"id": "a_pink", "label": "Pink", "kw": ["pink", "magenta", "fuchsia"], "hex": "#ff5fa2"},
    {"id": "a_gold", "label": "Gold", "kw": ["gold", "yellow", "champagne"], "hex": "#f3c969"},
    {"id": "a_red", "label": "Red", "kw": ["red", "crimson", "scarlet"], "hex": "#ff5a5f"},
    {"id": "a_cyan", "label": "Cyan", "kw": ["cyan", "teal", "aqua", "turquoise"], "hex": "#22d3ee"},
]

GROUPS = [
    {"key": "assets", "title": "Coins and tokens", "items": ASSETS, "multi": True},
    {"key": "networks", "title": "Networks", "items": NETWORKS, "multi": True},
    {"key": "custody", "title": "Custody model", "items": CUSTODY, "multi": False},
    {"key": "security", "title": "Security", "items": SECURITY, "multi": True},
    {"key": "features", "title": "Features", "items": FEATURES, "multi": True},
    {"key": "platforms", "title": "Platforms", "items": PLATFORMS, "multi": True},
    {"key": "privacy", "title": "Privacy", "items": PRIVACY, "multi": True},
    {"key": "style", "title": "Look and feel", "items": STYLES, "multi": False},
]

BY_ID = {}
for _g in GROUPS:
    for _it in _g["items"]:
        BY_ID[_it["id"]] = dict(_it, group=_g["key"])
for _it in THEMES + ACCENTS:
    BY_ID[_it["id"]] = dict(_it, group="theme" if _it["id"].startswith("t_") else "accent")

TOTAL_OPTIONS = len(BY_ID)


def label(oid: str) -> str:
    o = BY_ID.get(oid)
    return o["label"] if o else oid


def blurb(oid: str) -> str:
    o = BY_ID.get(oid)
    return o.get("blurb", "") if o else ""
